(() => {
'use strict';
const CFG=window.APSPP_CONFIG||{};
const API=(CFG.API_URL||'').trim();
const DEMO=!API && CFG.DEMO_IF_NO_API!==false;
const $=(q,root=document)=>root.querySelector(q); const $$=(q,root=document)=>[...root.querySelectorAll(q)];
const store={get:(k,d=null)=>{try{const v=localStorage.getItem(k);return v===null?d:JSON.parse(v)}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v)),del:k=>localStorage.removeItem(k)};
const state={key:store.get('apspp.key',''),officer:store.get('apspp.officer',''),bootstrap:null,cases:[],currentCase:null,currentActions:[],demo:DEMO};
const ACTION_LABELS={
INSPECTION:'Pemeriksaan premis',BREEDING_POSITIVE:'Pembiakan positif',COMPOUNDABLE_YES:'Premis boleh dikompaun',COMPOUNDABLE_NO:'Premis tidak boleh dikompaun',NOTICE_S6_ISSUED:'Notis Seksyen 6 dikeluarkan',FLOW_PAPER_VECTOR:'Flow paper di Unit Vektor',LARVA_RESULT:'Keputusan pemeriksaan larva',IP_OPENED:'Kertas siasatan dibuka',IP_SENT_UIPD:'Kertas siasatan dihantar ke UIPD',IP_SENT_CIPN_COMPOUND_PERMISSION:'Kertas siasatan dihantar ke CIPN untuk izin kompaun',IP_RETURNED_CORRECTION:'Kertas siasatan dipulangkan untuk pembetulan',COMPOUND_PERMISSION:'Izin mengkompaun diterima',PROSECUTION_PERMISSION:'Izin mendakwa diterima',COMPOUND_ISSUED:'Kompaun dikeluarkan',COMPOUND_PAID:'Kompaun dibayar',COMPOUND_EXPIRED_UNPAID:'Kompaun tamat tempoh tanpa bayaran',TPR_NFA:'NFA oleh TPR',COURT_REGISTERED:'Kes didaftarkan di mahkamah',COURT_FINE:'Mahkamah - denda',COURT_PRISON:'Mahkamah - penjara',COURT_FINE_PRISON:'Mahkamah - denda dan penjara',COURT_AD:'Mahkamah - A & D',COURT_DNAA:'Mahkamah - DNAA',COURT_WITHDRAWN:'Mahkamah - tarik balik',NOTICE_S8_ISSUED:'Perintah Notis Seksyen 8 dikeluarkan',NOTICE_S8_NONCOMPLIANCE:'Tidak mematuhi Notis Seksyen 8',COURT_S8_ACTION:'Tindakan mahkamah - Notis Seksyen 8',COURT_S8_CONVICTED:'Disabitkan - Notis Seksyen 8',COURT_S8_FINE:'Seksyen 8 - denda',COURT_S8_PRISON:'Seksyen 8 - penjara',COURT_S8_FINE_PRISON:'Seksyen 8 - denda dan penjara',COURT_S8_AD:'Seksyen 8 - A & D',COURT_S8_DNAA:'Seksyen 8 - DNAA',COURT_S8_WITHDRAWN:'Seksyen 8 - tarik balik',PREMISE_CLOSED_S8_3_AA:'Premis ditutup bawah 8(3)(aa)',CLOSURE_BREACH:'Engkar perintah penutupan',COURT_CLOSURE_ACTION:'Tindakan mahkamah - engkar penutupan',COURT_CLOSURE_CONVICTED:'Disabitkan - engkar penutupan',COURT_CLOSURE_FINE:'Engkar penutupan - denda',COURT_CLOSURE_PRISON:'Engkar penutupan - penjara',COURT_CLOSURE_FINE_PRISON:'Engkar penutupan - denda dan penjara',COURT_CLOSURE_AD:'Engkar penutupan - A & D',COURT_CLOSURE_DNAA:'Engkar penutupan - DNAA',COURT_CLOSURE_WITHDRAWN:'Engkar penutupan - tarik balik',CASE_CLOSED:'Kertas siasatan ditutup'};
const RETEN=[
[1,'Bil. premis yang diperiksa','INSPECTION','count',1],[2,'Bil. premis yang positif pembiakan','BREEDING_POSITIVE','count',1],[3,'Bil. premis boleh dikompaun','COMPOUNDABLE_YES','count',1],[4,'Bil. Premis tidak boleh dikompaun','COMPOUNDABLE_NO','count',1],[5,'Bil. Notis (Seksyen 6) dikeluarkan','NOTICE_S6_ISSUED','count',1],[6,'Jumlah flow paper di Unit Vektor','FLOW_PAPER_VECTOR','count',1],[7,'Bil. kertas siasatan dihantar ke UIPD','IP_SENT_UIPD','count'],[8,'Bil. kertas siasatan dihantar ke CIPN (untuk izin kompaun)','IP_SENT_CIPN_COMPOUND_PERMISSION','count'],[9,'Bil. kertas siasatan dari CIPN ke UIPD (untuk pembetulan)','IP_RETURNED_CORRECTION','count'],[10,'Bil. kompaun yang dikeluarkan','COMPOUND_ISSUED','count'],[11,'Jumlah amaun kompaun ditawarkan (RM)','COMPOUND_ISSUED','sum'],[12,'Bil. kompaun yang dibayar','COMPOUND_PAID','count'],[13,'Jumlah amaun kompaun yang dibayar (RM)','COMPOUND_PAID','sum'],[14,'Peratusan kompaun dibayar (%)','PERCENT','percent'],[15,'Bil. kompaun telah tamat tempoh yang tidak dijelaskan bayaran','COMPOUND_EXPIRED_UNPAID','count'],[16,'Bil. kes NFA oleh TPR','TPR_NFA','count'],[17,'Bil. kes daftar di Mahkamah','COURT_REGISTERED','count'],[18,'Bil. kes di denda','COURT_FINE','count'],[19,'Amaun didenda (RM)','COURT_FINE','sum'],[20,'Bil. kes di penjara','COURT_PRISON','count'],[21,'Bil. kes di denda dan penjara','COURT_FINE_PRISON','count'],[22,'Bil. kes A & D','COURT_AD','count'],[23,'Bil. kes DNAA','COURT_DNAA','count'],[24,'Bil. kes ditarik balik','COURT_WITHDRAWN','count'],[25,'Bil. Perintah Notis (Seksyen 8) dikeluarkan','NOTICE_S8_ISSUED','count',1],[26,'Bil. premis tidak mematuhi Notis Seksyen 8','NOTICE_S8_NONCOMPLIANCE','count',1],[27,'Bil. tindakan mahkamah atas kesalahan Notis Sek.8','COURT_S8_ACTION','count'],[28,'Bil. disabitkan kesalahan di mahkamah','COURT_S8_CONVICTED','count'],[29,'Bil. kes di denda','COURT_S8_FINE','count'],[30,'Amaun didenda (RM)','COURT_S8_FINE','sum'],[31,'Bil. kes di penjara','COURT_S8_PRISON','count'],[32,'Bil. kes di denda dan penjara','COURT_S8_FINE_PRISON','count'],[33,'Bil. kes A & D','COURT_S8_AD','count'],[34,'Bil. kes DNAA','COURT_S8_DNAA','count'],[35,'Bil. kes ditarik balik','COURT_S8_WITHDRAWN','count'],[36,'Bil. premis ditutup dibawah Seksyen perenggan 8(3)(aa)','PREMISE_CLOSED_S8_3_AA','count',1],[37,'Bil Premis engkar perintah penutupan','CLOSURE_BREACH','count',1],[38,'Bil. tindakan mahkamah atas kesalahan engkar perintah penutupan','COURT_CLOSURE_ACTION','count'],[39,'Bil. disabitkan kesalahan di mahkamah','COURT_CLOSURE_CONVICTED','count'],[40,'Bil. kes di denda','COURT_CLOSURE_FINE','count'],[41,'Amaun didenda (RM)','COURT_CLOSURE_FINE','sum'],[42,'Bil. kes di penjara','COURT_CLOSURE_PRISON','count'],[43,'Bil. kes di denda dan penjara','COURT_CLOSURE_FINE_PRISON','count'],[44,'Bil. kes A & D','COURT_CLOSURE_AD','count'],[45,'Bil. kes DNAA','COURT_CLOSURE_DNAA','count'],[46,'Bil. kes ditarik balik','COURT_CLOSURE_WITHDRAWN','count']];
function uuid(prefix='ID'){return prefix+'-'+(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2)).replaceAll('-','').slice(0,16).toUpperCase()}
function today(){return new Date().toISOString().slice(0,10)}
function nowLocalInput(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
function toast(msg,error=false){const t=$('#toast');t.textContent=msg;t.className='toast show'+(error?' error':'');clearTimeout(toast._t);toast._t=setTimeout(()=>t.className='toast',3200)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(n){return new Intl.NumberFormat('ms-MY',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n||0))}
function statusClass(s){return s==='SELESAI'?'ok':(/LEWAT|KOMPAUN|MAHKAMAH/.test(s||'')?'warn':'')}
function setOnlineDot(){const d=$('#syncDot');if(!d)return;d.classList.toggle('offline',!navigator.onLine)}
window.addEventListener('online',()=>{setOnlineDot();flushQueue()});window.addEventListener('offline',setOnlineDot);

function jsonp(action,params={}){return new Promise((resolve,reject)=>{if(DEMO){resolve(demoGet(action,params));return}const cb='__apspp_cb_'+Date.now()+'_'+Math.floor(Math.random()*9999);const script=document.createElement('script');const timer=setTimeout(()=>done(new Error('Backend tidak memberi respons.')),15000);function done(err,data){clearTimeout(timer);delete window[cb];script.remove();err?reject(err):resolve(data)}window[cb]=(r)=>r&&r.ok?done(null,r.data):done(new Error(r&&r.error||'Ralat backend'));const u=new URL(API);u.searchParams.set('action',action);u.searchParams.set('key',state.key);u.searchParams.set('callback',cb);Object.entries(params).forEach(([k,v])=>{if(v!==''&&v!==null&&v!==undefined)u.searchParams.set(k,v)});script.onerror=()=>done(new Error('Gagal menghubungi backend.'));script.src=u.toString();document.body.appendChild(script)})}
async function post(action,data){if(DEMO)return demoPost(action,data);const payload={action,data,key:state.key,officerId:state.officer};if(!navigator.onLine){queuePost(payload);return {queued:true}}try{const r=await fetch(API,{method:'POST',redirect:'follow',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});const text=await r.text();const j=JSON.parse(text);if(!j.ok)throw new Error(j.error||'Ralat backend');return j.data}catch(err){submitHidden(payload);return {submitted:true,noResponse:true,error:String(err.message||err)}}}
function submitHidden(payload){let iframe=$('#apsppPostFrame');if(!iframe){iframe=document.createElement('iframe');iframe.id='apsppPostFrame';iframe.name='apsppPostFrame';iframe.hidden=true;document.body.appendChild(iframe)}const f=document.createElement('form');f.method='POST';f.action=API;f.target='apsppPostFrame';const p=document.createElement('input');p.type='hidden';p.name='payload';p.value=JSON.stringify(payload);f.appendChild(p);document.body.appendChild(f);f.submit();f.remove()}
function queuePost(payload){const q=store.get('apspp.queue',[]);q.push(payload);store.set('apspp.queue',q);toast('Tiada internet. Tindakan disimpan dalam queue peranti.')}
async function flushQueue(){if(DEMO||!navigator.onLine)return;const q=store.get('apspp.queue',[]);if(!q.length)return;const remain=[];for(const p of q){try{await post(p.action,p.data)}catch{remain.push(p)}}store.set('apspp.queue',remain);if(!remain.length)toast('Queue offline telah dihantar.')}

function nav(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+view));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='dashboard')loadDashboard();if(view==='cases')loadCases();if(view==='reten')previewReten();window.scrollTo({top:0,behavior:'smooth'})}
async function login(){state.officer=$('#loginOfficer').value.trim();state.key=$('#loginKey').value.trim();if(!state.officer)return toast('Masukkan ID / nama pegawai.',true);if(!DEMO&&!state.key)return toast('Masukkan kunci akses.',true);try{state.bootstrap=await jsonp('bootstrap');store.set('apspp.officer',state.officer);store.set('apspp.key',state.key);$('#authScreen').classList.add('hidden');$('#appShell').classList.remove('hidden');$('#officerName').textContent=state.officer;$('#apiUrlView').value=API||'(Demo / belum disambung)';$('#officerView').value=state.officer;$('#modeView').value=DEMO?'DEMO LOCAL':'BACKEND GOOGLE';populateActionTypes();nav('dashboard');setOnlineDot();flushQueue()}catch(e){toast(e.message,true)}}
function logout(){store.del('apspp.key');store.del('apspp.officer');location.reload()}

async function loadDashboard(){try{const d=await jsonp('dashboard');$('#kpiActive').textContent=d.active||0;$('#kpiOverdue').textContent=d.overdue||0;$('#kpiActions').textContent=d.actionsThisWeek||0;$('#kpiWeek').textContent='ME '+(d.currentEpiWeek||'—');$('#kpiClosed').textContent=d.closed||0;renderStatusBars(d.byStatus||{});const cases=await jsonp('cases',{limit:80});state.cases=cases;renderAttention(cases)}catch(e){toast(e.message,true)}}
function renderAttention(cases){const now=new Date(today());const list=cases.filter(c=>c.CURRENT_STATUS!=='SELESAI').sort((a,b)=>String(a.NEXT_DUE_DATE||'9999').localeCompare(String(b.NEXT_DUE_DATE||'9999'))).slice(0,6);$('#attentionList').innerHTML=list.length?list.map(c=>{const overdue=c.NEXT_DUE_DATE&&new Date(c.NEXT_DUE_DATE)<now;return `<div class="case-card" data-case="${esc(c.CASE_ID)}"><div><h4>${esc(c.CASE_ID)} · ${esc(c.OKN_NAME||'Tanpa nama')}</h4><p>${esc(c.NEXT_ACTION||c.CURRENT_STATUS||'')}</p></div><span class="badge ${overdue?'warn':''}">${overdue?'LEWAT':esc(c.NEXT_DUE_DATE||c.CURRENT_STATUS||'AKTIF')}</span></div>`}).join(''):'<p class="muted">Tiada kes aktif.</p>';bindCaseClicks()}
function renderStatusBars(by){const entries=Object.entries(by).sort((a,b)=>b[1]-a[1]);const max=Math.max(1,...entries.map(x=>x[1]));$('#statusBars').innerHTML=entries.length?entries.map(([s,n])=>`<div class="status-row"><span>${esc(s)}</span><div class="bar"><i style="width:${Math.round(n/max*100)}%"></i></div><b>${n}</b></div>`).join(''):'<p class="muted">Belum ada data.</p>'}

async function createCase(ev){ev.preventDefault();const fd=new FormData(ev.currentTarget);const d=Object.fromEntries(fd.entries());const req=uuid('REQ');const actionDate=(d.OFFENCE_DATETIME||nowLocalInput()).slice(0,10);const initial=[{ACTION_ID:uuid('ACT'),ACTION_TYPE:'INSPECTION',ACTION_DATE:actionDate,NOTES:'Pemeriksaan awal',OFFICER_ID:state.officer}];if(d.BREEDING_FOUND==='YES')initial.push({ACTION_ID:uuid('ACT'),ACTION_TYPE:'BREEDING_POSITIVE',ACTION_DATE:actionDate,NOTES:d.LARVA_TYPE||'Pembiakan dijumpai',OFFICER_ID:state.officer});if(d.COMPOUNDABLE==='YES')initial.push({ACTION_ID:uuid('ACT'),ACTION_TYPE:'COMPOUNDABLE_YES',ACTION_DATE:actionDate,OFFICER_ID:state.officer});if(d.COMPOUNDABLE==='NO')initial.push({ACTION_ID:uuid('ACT'),ACTION_TYPE:'COMPOUNDABLE_NO',ACTION_DATE:actionDate,OFFICER_ID:state.officer});if(d.NOTICE_DATE)initial.push({ACTION_ID:uuid('ACT'),ACTION_TYPE:'NOTICE_S6_ISSUED',ACTION_DATE:d.NOTICE_DATE,REF_NO:d.NOTICE_NO||'',OFFICER_ID:state.officer});const payload={CLIENT_REQUEST_ID:req,CASE_TYPE:'APSPP',CURRENT_STATUS:d.BREEDING_FOUND==='YES'?'MENUNGGU KEPUTUSAN LARVA':'BARU',RETEN_LOCALITY_CATEGORY:d.RETEN_LOCALITY_CATEGORY,AREA_STATUS:d.AREA_STATUS,NOTICE_NO:d.NOTICE_NO,OKN_NAME:d.OKN_NAME,ID_TYPE:d.ID_TYPE,ID_NO:d.ID_NO,ADDRESS:d.ADDRESS,OFFENCE_RULE:d.OFFENCE_RULE,OFFENCE_DATETIME:d.OFFENCE_DATETIME,BREEDING_PLACE:d.BREEDING_PLACE,LARVA_TYPE:d.LARVA_TYPE,LARVA_COUNT:d.LARVA_COUNT,CURRENT_OWNER_OFFICER_ID:state.officer,NEXT_ACTION:d.NEXT_ACTION,NEXT_DUE_DATE:d.NEXT_DUE_DATE,NOTES:d.NOTES,OFFICER_ID:state.officer,initialActions:initial};try{const r=await post('createCase',payload);ev.currentTarget.reset();ev.currentTarget.elements.OFFENCE_DATETIME.value=nowLocalInput();if(r&&r.CASE_ID){toast('Kes '+r.CASE_ID+' berjaya disimpan.');await openCase(r.CASE_ID)}else{toast(r&&r.queued?'Kes disimpan dalam queue offline.':'Kes dihantar. Segarkan senarai untuk dapat CASE_ID.');nav('cases')}}catch(e){toast(e.message,true)}}

async function loadCases(){try{const q=$('#caseSearch')?.value||'';const st=$('#statusFilter')?.value||'';state.cases=await jsonp('cases',{search:q,status:st,limit:300});renderCases(state.cases)}catch(e){toast(e.message,true)}}
function renderCases(cases){$('#caseList').innerHTML=cases.length?cases.map(c=>`<div class="case-row" data-case="${esc(c.CASE_ID)}"><div><strong>${esc(c.CASE_ID)}</strong><small>${esc(c.OKN_NAME||'')}</small></div><div class="hide-mobile"><strong>${esc(c.ADDRESS||'')}</strong><small>${esc(c.NOTICE_NO||c.IP_REF||'')}</small></div><div class="hide-mobile"><span class="badge">${esc(c.RETEN_LOCALITY_CATEGORY||'')}</span></div><div><span class="badge ${statusClass(c.CURRENT_STATUS)}">${esc(c.CURRENT_STATUS||'BARU')}</span><small>${esc(c.NEXT_DUE_DATE||'')}</small></div><span>›</span></div>`).join(''):'<p class="muted">Tiada kes dijumpai.</p>';bindCaseClicks()}
function bindCaseClicks(){$$('[data-case]').forEach(x=>x.onclick=()=>openCase(x.dataset.case))}
async function openCase(id){try{const d=await jsonp('case',{caseId:id});state.currentCase=d.case;state.currentActions=d.actions||[];renderCaseDetail();nav('case-detail')}catch(e){toast(e.message,true)}}
function renderCaseDetail(){const c=state.currentCase;$('#detailCaseId').textContent=c.CASE_ID;$('#detailSubtitle').textContent=(c.OKN_NAME||'')+' · '+(c.CURRENT_STATUS||'');const fields=[['Status',c.CURRENT_STATUS],['OKN / Premis',c.OKN_NAME],['No. Notis',c.NOTICE_NO],['IC/SSM/ID',c.ID_NO],['Alamat',c.ADDRESS],['Klasifikasi',c.RETEN_LOCALITY_CATEGORY],['Status kawasan',c.AREA_STATUS],['Kesalahan',c.OFFENCE_RULE],['Tempat pembiakan',c.BREEDING_PLACE],['Larva',c.LARVA_TYPE],['No. IP',c.IP_REF],['Next action',c.NEXT_ACTION],['Due date',c.NEXT_DUE_DATE],['Pegawai semasa',c.CURRENT_OWNER_OFFICER_ID]];$('#caseSummary').innerHTML='<div class="panel-head"><h3>Ringkasan Kes</h3><span class="badge '+statusClass(c.CURRENT_STATUS)+'">'+esc(c.CURRENT_STATUS||'')+'</span></div><dl class="summary-list">'+fields.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v||'—')}</dd>`).join('')+'</dl>';$('#timeline').innerHTML=state.currentActions.length?state.currentActions.map(a=>`<div class="timeline-item"><h4>${esc(a.ACTION_LABEL||ACTION_LABELS[a.ACTION_TYPE]||a.ACTION_TYPE)}</h4><p>${esc(a.ACTION_DATE||a.ACTION_AT||'')} · ${esc(a.OFFICER_ID||'')}</p>${a.REF_NO?`<p>Rujukan: ${esc(a.REF_NO)}</p>`:''}${Number(a.AMOUNT)>0?`<p class="amount">RM ${money(a.AMOUNT)}</p>`:''}${a.NOTES?`<p>${esc(a.NOTES)}</p>`:''}</div>`).join(''):'<p class="muted">Belum ada timeline.</p>';$('#actionForm').classList.add('hidden');$('#actionForm').elements.ACTION_DATE.value=today()}
function populateActionTypes(){const sel=$('#actionType');sel.innerHTML=Object.entries(ACTION_LABELS).map(([v,l])=>`<option value="${v}">${esc(l)}</option>`).join('')}
async function addAction(ev){ev.preventDefault();if(!state.currentCase)return;const d=Object.fromEntries(new FormData(ev.currentTarget).entries());d.ACTION_ID=uuid('ACT');d.CASE_ID=state.currentCase.CASE_ID;d.RETEN_LOCALITY_CATEGORY=state.currentCase.RETEN_LOCALITY_CATEGORY;d.OFFICER_ID=state.officer;try{const r=await post('addAction',d);toast(r&&r.queued?'Tindakan masuk queue offline.':'Tindakan disimpan.');await openCase(state.currentCase.CASE_ID)}catch(e){toast(e.message,true)}}

function currentEpiWeek(){const y=new Date().getFullYear();const jan1=new Date(y,0,1),day=jan1.getDay(),add=day===0?0:7-day,first=new Date(y,0,1+add),d=new Date();if(d<first)return 0;return Math.floor((new Date(d.getFullYear(),d.getMonth(),d.getDate())-first)/86400000/7)+1}
async function previewReten(){const year=Number($('#retenYear').value||CFG.YEAR||2026),week=Number($('#retenWeek').value||currentEpiWeek());try{const d=await jsonp('retenPreview',{year,week});renderReten(d)}catch(e){toast(e.message,true)}}
function renderReten(d){$('#retenRange').textContent='ME '+d.week+' · '+(d.range||'');$('#retenPreview').innerHTML='<div class="reten-row head"><span>Bil.</span><span>Aktiviti</span><span class="num">ME '+d.week+'</span></div>'+d.rows.map(r=>`<div class="reten-row"><span>${r.no}</span><span>${esc(r.label)}${r.detail?`<div class="reten-detail">Satu Kes ${r.detail.SATU_KES||0} · Wabak ${r.detail.WABAK||0} · Wolbachia ${r.detail.WOLBACHIA||0}</div>`:''}</span><span class="num">${r.no===14?(Number(r.value||0)*100).toFixed(1)+'%':(r.no===11||r.no===13||r.no===19||r.no===30||r.no===41?'RM '+money(r.value):esc(r.value||0))}</span></div>`).join('')}
async function generateReten(){if(DEMO){toast('Mod demo tidak menghasilkan XLSX. Sambungkan Apps Script untuk fungsi ini.',true);return}const year=Number($('#retenYear').value),week=Number($('#retenWeek').value);$('#generateRetenBtn').disabled=true;try{const r=await post('generateReten',{year,week});const box=$('#retenResult');box.classList.remove('hidden');if(r&&r.url)box.innerHTML=`<div class="result-success"><b>Excel berjaya dijana.</b><br><a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.fileName||'Buka fail di Google Drive')}</a></div>`;else box.innerHTML='<div class="result-success"><b>Permintaan jana Excel telah dihantar.</b><br>Jika browser menyekat respons silang-domain, semak folder <b>Reten Excel</b> dalam Google Drive.</div>';toast('Reten ME'+week+' diproses.')}catch(e){toast(e.message,true)}finally{$('#generateRetenBtn').disabled=false}}

function seedDemo(){if(store.get('apspp.demo.seeded'))return;const c=[{CASE_ID:'APSPP-PKT-2026-0037',CLIENT_REQUEST_ID:'D1',CREATED_AT:'2026-09-05T09:10:00+08:00',UPDATED_AT:'2026-09-07T10:20:00+08:00',CURRENT_STATUS:'DI UIPD',RETEN_LOCALITY_CATEGORY:'WABAK',AREA_STATUS:'WABAK TERKAWAL',NOTICE_NO:'A 4027',OKN_NAME:'Premis Contoh A',ID_TYPE:'SSM',ID_NO:'DEMO-001',ADDRESS:'Titiwangsa, Kuala Lumpur',OFFENCE_RULE:'13(1)',OFFENCE_DATETIME:'2026-09-05T09:10',BREEDING_PLACE:'bekas plastik',LARVA_TYPE:'Aedes aegypti',LARVA_COUNT:5,IP_REF:'PKT / 37 / 2026 / V',CURRENT_OWNER_OFFICER_ID:'PKT-DEMO',NEXT_ACTION:'Menunggu semakan UIPD',NEXT_DUE_DATE:'2026-09-10'},{CASE_ID:'APSPP-PKT-2026-0038',CLIENT_REQUEST_ID:'D2',CREATED_AT:'2026-09-06T15:00:00+08:00',UPDATED_AT:'2026-09-06T15:00:00+08:00',CURRENT_STATUS:'MENUNGGU KEPUTUSAN LARVA',RETEN_LOCALITY_CATEGORY:'SATU_KES',AREA_STATUS:'BUKAN WABAK',NOTICE_NO:'A 4028',OKN_NAME:'Premis Contoh B',ID_TYPE:'Kad Pengenalan',ID_NO:'DEMO-002',ADDRESS:'Setapak, Kuala Lumpur',OFFENCE_RULE:'13(1)',OFFENCE_DATETIME:'2026-09-06T15:00',BREEDING_PLACE:'tong air',CURRENT_OWNER_OFFICER_ID:'PKT-DEMO',NEXT_ACTION:'Terima keputusan larva',NEXT_DUE_DATE:'2026-09-08'},{CASE_ID:'APSPP-PKT-2026-0032',CLIENT_REQUEST_ID:'D3',CREATED_AT:'2026-08-26T11:00:00+08:00',UPDATED_AT:'2026-09-04T10:00:00+08:00',CURRENT_STATUS:'SELESAI',RETEN_LOCALITY_CATEGORY:'WABAK',AREA_STATUS:'HOTSPOT',NOTICE_NO:'A 4022',OKN_NAME:'Premis Contoh C',ADDRESS:'Kampung Baru, Kuala Lumpur',OFFENCE_RULE:'13(1)',CURRENT_OWNER_OFFICER_ID:'PKT-DEMO',NEXT_ACTION:'',NEXT_DUE_DATE:''}];const a=[demoA('0037','INSPECTION','2026-09-05','WABAK'),demoA('0037','BREEDING_POSITIVE','2026-09-05','WABAK'),demoA('0037','NOTICE_S6_ISSUED','2026-09-05','WABAK'),demoA('0037','IP_OPENED','2026-09-06','WABAK'),demoA('0037','IP_SENT_UIPD','2026-09-07','WABAK'),demoA('0038','INSPECTION','2026-09-06','SATU_KES'),demoA('0038','BREEDING_POSITIVE','2026-09-06','SATU_KES'),demoA('0038','NOTICE_S6_ISSUED','2026-09-06','SATU_KES'),demoA('0032','COMPOUND_ISSUED','2026-09-01','WABAK',500),demoA('0032','COMPOUND_PAID','2026-09-04','WABAK',500),demoA('0032','CASE_CLOSED','2026-09-04','WABAK')];store.set('apspp.demo.cases',c);store.set('apspp.demo.actions',a);store.set('apspp.demo.seeded',true)}
function demoA(num,type,date,cat,amount=0){return{ACTION_ID:uuid('DA'),CASE_ID:'APSPP-PKT-2026-'+num,ACTION_AT:date+'T12:00:00+08:00',ACTION_DATE:date,EPID_WEEK:epiWeekDate(new Date(date+'T12:00:00')),ACTION_TYPE:type,ACTION_LABEL:ACTION_LABELS[type],RETEN_LOCALITY_CATEGORY:cat,AMOUNT:amount,OFFICER_ID:'PKT-DEMO'}}
function epiWeekDate(d){const y=d.getFullYear(),j=new Date(y,0,1),add=j.getDay()===0?0:7-j.getDay(),f=new Date(y,0,1+add);return d<f?0:Math.floor((new Date(y,d.getMonth(),d.getDate())-f)/86400000/7)+1}
function demoGet(action,p){seedDemo();const cases=store.get('apspp.demo.cases',[]),actions=store.get('apspp.demo.actions',[]);if(action==='bootstrap')return{app:{name:CFG.APP_NAME,version:'DEMO',district:CFG.DISTRICT,currentEpiWeek:currentEpiWeek()},lookups:[],officers:[]};if(action==='cases'){let x=cases;if(p.status)x=x.filter(c=>c.CURRENT_STATUS===p.status);if(p.search){const s=String(p.search).toLowerCase();x=x.filter(c=>Object.values(c).some(v=>String(v||'').toLowerCase().includes(s)))}return x.sort((a,b)=>String(b.UPDATED_AT).localeCompare(String(a.UPDATED_AT)))}if(action==='case'){const c=cases.find(c=>c.CASE_ID===p.caseId);const a=actions.filter(a=>a.CASE_ID===p.caseId).sort((x,y)=>String(x.ACTION_AT).localeCompare(String(y.ACTION_AT)));return{case:c,actions:a.map(x=>({...x,ACTION_LABEL:ACTION_LABELS[x.ACTION_TYPE]||x.ACTION_TYPE}))}}if(action==='dashboard'){const active=cases.filter(c=>c.CURRENT_STATUS!=='SELESAI').length,closed=cases.length-active,now=new Date(today()),overdue=cases.filter(c=>c.CURRENT_STATUS!=='SELESAI'&&c.NEXT_DUE_DATE&&new Date(c.NEXT_DUE_DATE)<now).length,w=currentEpiWeek(),byStatus={};cases.forEach(c=>byStatus[c.CURRENT_STATUS]=(byStatus[c.CURRENT_STATUS]||0)+1);return{totalCases:cases.length,active,closed,overdue,currentEpiWeek:w,actionsThisWeek:actions.filter(a=>Number(a.EPID_WEEK)===w).length,byStatus}}if(action==='retenPreview')return demoReten(Number(p.year),Number(p.week),actions);throw new Error('Demo GET action tidak dikenali')}
function demoPost(action,d){seedDemo();if(action==='createCase'){let cases=store.get('apspp.demo.cases',[]),actions=store.get('apspp.demo.actions',[]);const old=cases.find(c=>c.CLIENT_REQUEST_ID===d.CLIENT_REQUEST_ID);if(old)return Promise.resolve({CASE_ID:old.CASE_ID,duplicate:true});const max=Math.max(0,...cases.map(c=>Number(String(c.CASE_ID).split('-').pop())||0)),id='APSPP-PKT-2026-'+String(max+1).padStart(4,'0');const now=new Date().toISOString();const c={...d,CASE_ID:id,CREATED_AT:now,UPDATED_AT:now};delete c.initialActions;delete c.OFFICER_ID;cases.push(c);(d.initialActions||[]).forEach(a=>actions.push({...a,CASE_ID:id,ACTION_AT:a.ACTION_DATE+'T12:00:00+08:00',EPID_WEEK:epiWeekDate(new Date(a.ACTION_DATE+'T12:00:00')),RETEN_LOCALITY_CATEGORY:d.RETEN_LOCALITY_CATEGORY,ACTION_LABEL:ACTION_LABELS[a.ACTION_TYPE]}));store.set('apspp.demo.cases',cases);store.set('apspp.demo.actions',actions);return Promise.resolve({CASE_ID:id})}if(action==='addAction'){let cases=store.get('apspp.demo.cases',[]),actions=store.get('apspp.demo.actions',[]);if(actions.some(a=>a.ACTION_ID===d.ACTION_ID))return Promise.resolve({ACTION_ID:d.ACTION_ID,duplicate:true});actions.push({...d,ACTION_AT:d.ACTION_DATE+'T12:00:00+08:00',EPID_WEEK:epiWeekDate(new Date(d.ACTION_DATE+'T12:00:00')),ACTION_LABEL:ACTION_LABELS[d.ACTION_TYPE]});const c=cases.find(c=>c.CASE_ID===d.CASE_ID);if(c){c.UPDATED_AT=new Date().toISOString();const sm={LARVA_RESULT:'PERLU BUKA KERTAS SIASATAN',IP_OPENED:'DI UNIT VEKTOR',IP_SENT_UIPD:'DI UIPD',IP_SENT_CIPN_COMPOUND_PERMISSION:'DI JKN',COMPOUND_ISSUED:'TINDAKAN KOMPAUN',COURT_REGISTERED:'TINDAKAN MAHKAMAH',CASE_CLOSED:'SELESAI'};if(sm[d.ACTION_TYPE])c.CURRENT_STATUS=sm[d.ACTION_TYPE];if(d.NEXT_ACTION!==undefined)c.NEXT_ACTION=d.NEXT_ACTION;if(d.DUE_DATE)c.NEXT_DUE_DATE=d.DUE_DATE}store.set('apspp.demo.cases',cases);store.set('apspp.demo.actions',actions);return Promise.resolve({ACTION_ID:d.ACTION_ID})}return Promise.reject(new Error('Demo POST action tidak dikenali'))}
function demoReten(year,week,actions){const aa=actions.filter(a=>String(a.ACTION_DATE||'').startsWith(String(year))&&Number(a.EPID_WEEK)===week);const value=(ind,cat)=>{if(ind[3]==='percent'){const i=aa.filter(a=>a.ACTION_TYPE==='COMPOUND_ISSUED').length,p=aa.filter(a=>a.ACTION_TYPE==='COMPOUND_PAID').length;return i?p/i:0}const list=aa.filter(a=>a.ACTION_TYPE===ind[2]&&(!cat||a.RETEN_LOCALITY_CATEGORY===cat));return ind[3]==='sum'?list.reduce((s,a)=>s+Number(a.AMOUNT||0),0):list.length};const rows=RETEN.map(ind=>{if(ind[4]){const detail={SATU_KES:value(ind,'SATU_KES'),WABAK:value(ind,'WABAK'),WOLBACHIA:value(ind,'WOLBACHIA')};return{no:ind[0],label:ind[1],value:detail.SATU_KES+detail.WABAK+detail.WOLBACHIA,detail}}return{no:ind[0],label:ind[1],value:value(ind)}});return{year,week,range:'Demo',rows}}

function init(){for(let w=1;w<=52;w++)$('#retenWeek').insertAdjacentHTML('beforeend',`<option value="${w}">ME ${w}</option>`);$('#retenWeek').value=Math.min(52,Math.max(1,currentEpiWeek()));$('#retenYear').value=CFG.YEAR||new Date().getFullYear();$('#newCaseForm').elements.OFFENCE_DATETIME.value=nowLocalInput();$('#actionForm').elements.ACTION_DATE.value=today();if(DEMO)$('#demoBadge').classList.remove('hidden');$$('[data-view]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.view)));$('#loginBtn').onclick=login;$('#logoutBtn').onclick=logout;$('#refreshBtn').onclick=loadDashboard;$('#newCaseForm').addEventListener('submit',createCase);$('#searchBtn').onclick=loadCases;$('#caseSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();loadCases()}});$('#statusFilter').onchange=loadCases;$('#openActionBtn').onclick=()=>$('#actionForm').classList.remove('hidden');$('#closeActionBtn').onclick=()=>$('#actionForm').classList.add('hidden');$('#actionForm').addEventListener('submit',addAction);$('#previewRetenBtn').onclick=previewReten;$('#generateRetenBtn').onclick=generateReten;$('#clearLocalBtn').onclick=()=>{if(confirm('Kosongkan data demo, session dan queue pada peranti ini?')){['apspp.demo.cases','apspp.demo.actions','apspp.demo.seeded','apspp.queue','apspp.key','apspp.officer'].forEach(store.del);location.reload()}};setOnlineDot();if(state.officer){$('#loginOfficer').value=state.officer;$('#loginKey').value=state.key;if(DEMO||state.key)login()}if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
document.addEventListener('DOMContentLoaded',init);
})();
